### ISSUE TITLE
The caption file only has 29999 captions

### ISSUE THREAD

**Issue by LonglongaaaGo** [ziqihuangg/CelebA-Dialog#1]
Hi,

Thank you so much for your awesome work.
Recently, I tried to read files in captions_hq.json.
But find there are only captions for 29999 images. 
Is there a missing file here?

**Comment by ziqihuangg** [comment]
Hi, this is because image 5380.jpg in CelebA-HQ is corrupted, so we didn't provide text annotations for it.

**Comment by LonglongaaaGo** [comment]
Hi @ziqihuangg ,

Thank you so much!
I got it.
